swagger: "2.0"
info:
  title: "Payment System"
  version: "2.0"
basePath: /paymentSystem/v1.0
paths:
  /paymentService:
    post:
      description: "Submit a payment or refund request"
      operationId: "submitPaymentServiceRequest"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/PaymentServiceRequest'
      responses:
        200:
          description: "Successful response"
          schema:
            $ref: '#/definitions/PaymentServiceResponse'
        400:
          description: "Bad Request: request input missing, wrong data type"
          schema:
            $ref: '#/definitions/ErrorResponse'
        500:
          description: "Internal Server Error"
          schema:
            $ref: '#/definitions/ErrorResponse'
        default:
          description: "Unexpected error"
          schema:
            $ref: '#/definitions/ErrorResponse'
definitions:
  PaymentServiceRequest:
    type: object
    properties:
      operation:
        description: 'Identifier to show type of request. i.e. payment/refund'
        type: string
      transactionCode:
        description: 'A unique code for a transaction'
        type: string
      amount:
        description: "Purchase amount for transaction"
        type: integer
      currencyCode:
        description: '3 digit ISO currency code'
        type: string
      cardDetails:
        $ref: '#/definitions/CardDetails'
      merchantDetails:
        $ref: '#/definitions/MerchantDetails'
      shopperDetails:
        $ref: '#/definitions/ShopperDetails'
  PaymentServiceResponse:
    type: object
    properties:
      transactionId:
        description: "The unique identifier for this transaction"
        type: string
  CardDetails:
      type: object
      required: [cardNumber, expiryMonth, expiryYear, cardholderName]
      properties:
        cardNumber:
          description: "Credit/debit card number"
          type: string
        expiryMonth:
          description: "Month of credit/debit card expiry"
          type: integer
        expiryYear:
          description: "Year of credit/debit card expiry"
          type: integer
        cvv:
          description: 'CVV on credit/debit card'
          type: string
        cardholderName:
          description: 'Name printed on credit/debit card'
          type: string
  MerchantDetails:
      type: object
      required: [merchantCode]
      properties:
        merchantCode:
          description: "Unique merchant code"
          type: string
  ShopperDetails:
      type: object
      required: [firstName, lastName, billingAddress, email]
      properties:
        firstName:
          description: 'Shopper first name'
          type: string
        lastName:
          description: 'Shopper last name'
          type: string
        billingAddress:
          description: 'Shopper billing address'
          $ref: '#/definitions/Address'
        email:
          description: 'Shopper email address'
          type: string
  Address:
    type: object
    properties:
      line1:
        description: "Address line 1"
        type: string
      line2:
        description: "Address line 2"
        type: string
      city:
        description: "Address city"
        type: string
      countryCode:
        description: "2 digit ISO country code"
        type: string
      firstName:
        description: "Address first name"
        type: string
      lastName:
        description: "Address last name"
        type: string
      phone:
        description: "Address telephone number"
        type: string
      postCode:
        description: "Address post code"
        type: string
      state:
        description: "Address state/county"
        type: string
  ErrorResponse:
      type: object
      required: [errorCode, errorMessage]
      properties:
        errorCode:
          type: string
        errorMessage:
          type: string
